### ISSUE TITLE
hg38 polymorphic STR catalog for GRCH38

### ISSUE THREAD

**Issue by hchetia** [Illumina/RepeatCatalogs#1]
Can we use the hg38 polymorphic STR catalog for GRCH38?

**Comment by yjqiu** [comment]
Yes. It has both hg38 and hg19 versions and you can use either of them. We have just updated it to a larger genome-wide catalog. Feel free to use it if you want to explore more functional STRs.

**Comment by hchetia** [comment]
thanks @yjqiu 
I see that you updated the catalog 3 hrs ago. I used the polymorphic STR catalog and poly STR exonic catalog this morning. Do I need to rerun my alignment files with the new catalog?

**Comment by yjqiu** [comment]
@hchetia It totally depends on you. The previous and updated one should all be of good quality. The updated one does have a lot more STRs though. If you are interested in genotyping more STRs, you may try the new one.

**Comment by hchetia** [comment]
@yjqiu thanks.
Could you also please clarify what the 1000 genome/genotype/tsv file entails?
Does the second field specify all the genotype predictions for a loci from 1000 genomes data? 
![image](https://user-images.githubusercontent.com/64626735/134103208-4baa8938-0ed5-4c47-ac22-ee53328d4b03.png)

**Comment by yjqiu** [comment]
@hchetia Thanks for double checking. I have updated the file to include header. The headers are "VariantId	RepeatNumbers	AlleleCounts". Allele counts for each repeat number is shown. Let me know if it is clear for you.
